version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
